### ISSUE TITLE
Checks fail with duckplyr

### ISSUE THREAD

**Issue by krlmlr** [dschafer/activatr#18]
The duckplyr package is aimed to be a drop-in replacement for dplyr, with full behavior compatibility. To assert that, I'm running checks with a rigged version of dplyr. This package fails its checks in this scenario.

Details: https://github.com/krlmlr/dplyr/blob/f-revdep-duckplyr/revdep/problems.md .

Learn more about duckplyr: https://duckplyr.tidyverse.org/ .

From the error message, I can't tell immediately what the cause of the failure is. I'd appreciate your help: can you please help digest a reproducible example that shows how duckplyr is behaving differently from dplyr in your use case?

The modified dplyr version can be installed with any of:

```r
pak::pak("krlmlr/dplyr@f-revdep-duckplyr")
# remotes::install_github("krlmlr/dplyr@f-revdep-duckplyr")
# devtools::install_github("krlmlr/dplyr@f-revdep-duckplyr")
```

Thanks a lot for your help! Please let me know if you have any questions.

Tracker: https://github.com/tidyverse/duckplyr/issues/297.

**Comment by dschafer** [comment]
Here's a reduced example. With `dplyr` 1.1.4:

``` r
library(tibble)
library(lubridate)
library(dplyr)
s <- tibble::tibble(x = 1)
time <- 1 |> as.duration()
s <- s |> mutate(Time = time)
is(s$Time)
#> [1] "Duration" "Timespan" "numeric"  "vector"
```

<sup>Created on 2024-11-01 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

With `krlmlr/dplyr@f-revdep-duckplyr`:

``` r
library(tibble)
library(lubridate)
library(dplyr)
s <- tibble::tibble(x = 1)
time <- 1 |> as.duration()
s <- s |> mutate(Time = time)
is(s$Time)
#> [1] "numeric" "vector"
```

<sup>Created on 2024-11-01 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by dschafer** [comment]
@krlmlr closing this out since hopefully that reduced example is what you were looking for (specifically, it looks like when a column is created with a lubridate Duration, the class is handled differently between dplyr and duckplyr)

**Comment by krlmlr** [comment]
Thank you very much for your support, this is very helpful!
